import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import "../style.css";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { getUserOrders } from "@/lib/getUserOrders";
import { Toaster } from "react-hot-toast";

const poppins = localFont({
  src: "../fonts/Poppins.woff2",
  variable: "--font-poppins",
  weight: "400",
  preload: false,
});

export const metadata: Metadata = {
  title: "Ecommerce App for Shoppers",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, orders } = await getUserOrders();

  return (
    <ClerkProvider>
      <html lang="en">
        <head></head>
        <body className={`${poppins.variable} antialiased`}>
          <Header user={JSON.parse(JSON.stringify(user))} orders={orders} />

          {children}
          <Footer />

          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#000000",
                color: "#fff",
              },
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
