export type Order = {
  orderNumber: string;
  clerkId: string;
  totalPrice: number;
  currencyCode: string;
  amountDiscount: number;
  orderStatusId: number;
  orderDate: string;
  trackingNumber: string;
  deliveryDate: string;
  shippingAddressId: number;
  street: string;
  city: string;
  provinceId: number | null;
  provinceName: string | null;
  stateId: number | null;
  stateName: string | null;
  postalCode: string;
  countryId: number;
  countryName: string;
};
